In [1]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
%matplotlib qt

In [13]:
def recoverTransformation(Image1, Image2):
    plt.figure()
    plt.imshow(Image1,cmap='gray')
    points_1=plt.ginput(6, timeout=120)
    plt.show()
    
    plt.figure()
    plt.imshow(Image2,cmap='gray')
    points_2=plt.ginput(6, timeout=120)
    plt.show()


    points_1=np.array(points_1)
    points_2=np.array(points_2)
    
    locs_1=points_1
    locs_2=points_2
     # Construct A matrix from selected locations of original image
    A= np.zeros((2*locs_1.shape[0], 6))
    print(A.shape)
    for count, i in enumerate(range(0, A.shape[0], 2)):  

        A[i,:]=   np.concatenate((locs_1[count,:], np.array([1,0,0,0])) , axis=0 )
        A[i+1,:]= np.concatenate(( np.array([0,0,0]) , locs_1[count,:] , np.array([1]) ) , axis=0 )

        
    # Getting y vector from corresponding locations in transformed image    
    y= locs_2.reshape((-1,1))

    
    # Getting transformation matrix
    A_pinv =  np.linalg.pinv(A)
    x= np.matmul(A_pinv,y)
    T = x.reshape(2,3) # transformation matrix
    
    
    # Applying affine transformation on original image
    T_Image= cv.warpAffine( Image1, T , (Image2.shape[1], Image2.shape[0]  ) )
    
    
    
    # Getting MSE between intensities of Image2 and transformed image
    MSEPix= np.mean( (T_Image-Image2)**2 )
    
    
    # Getting MSE between corresponding locations of Image2 and transformed locations
    T_points= np.matmul(T,  np.vstack( (locs_1.T, np.ones((1, locs_1.T.shape[1]))) ))
    MSECorPts = np.mean( (T_points-locs_2.T)**2 )
    
    
    return MSEPix, MSECorPts, T, T_Image
    
   

# Loading Image Arfa1

In [35]:
orignal=plt.imread('dataset/arfa1.jpg')
transformed=plt.imread('dataset/arfa2.jpg')
dim=orignal.ndim
dim2=transformed.ndim
if dim>2:
    orignal = cv.cvtColor(orignal, cv.COLOR_RGB2GRAY)
if dim2>2:
    orignal = cv.cvtColor(transformed, cv.COLOR_RGB2GRAY)

In [36]:
MSEpix,MSECorpts,T,T_image=recoverTransformation(orignal,transformed)

(12, 6)


In [37]:
print("MSEpix for pic arfa is ",MSEpix)
print("MSECorpts for pic arfa is ",MSECorpts)
print("T Matrix for pic arfa is \n",np.array(T))

MSEpix for pic arfa is  55.31878757455149
MSECorpts for pic arfa is  808.2413578895959
T Matrix for pic arfa is 
 [[  0.84846728  -0.637913   175.89480528]
 [  0.84078031   0.80771421 -25.55616228]]


In [38]:
#plt.imsave('results/arfa1_transformed.jpg',T_image,cmap='gray')

# Loading Image Mecca1

In [18]:
orignal=plt.imread('dataset/mecca1.jpg')
transformed=plt.imread('dataset/mecca2.jpg')
dim=orignal.ndim
dim2=transformed.ndim
if dim>2:
    orignal = cv.cvtColor(orignal, cv.COLOR_RGB2GRAY)
if dim2>2:
    transformed = cv.cvtColor(transformed, cv.COLOR_RGB2GRAY)

In [19]:
MSEpix,MSECorpts,T,T_image=recoverTransformation(orignal,transformed)
print("MSEpix for pic arfa is ",MSEpix)
print("MSECorpts for pic arfa is ",MSECorpts)
print("T Matrix for pic arfa is \n",np.array(T))

(12, 6)
MSEpix for pic arfa is  24.930153759685254
MSECorpts for pic arfa is  16.59444003064156
T Matrix for pic arfa is 
 [[ -0.62128735  -0.92216581 360.35829471]
 [  0.86648825  -0.62024069 164.27890655]]


In [21]:
#plt.imsave('results/mecca1_transformed.jpg',T_image,cmap='gray')

# Loading Station image 

In [22]:
orignal=plt.imread('dataset/station1.png')
transformed=plt.imread('dataset/station2.png')
dim=orignal.ndim
dim2=transformed.ndim
if dim>2:
    orignal = cv.cvtColor(orignal, cv.COLOR_RGB2GRAY)
if dim2>2:
    transformed = cv.cvtColor(transformed, cv.COLOR_RGB2GRAY)
print()

In [24]:
MSEpix,MSECorpts,T,T_image=recoverTransformation(orignal,transformed)
print("MSEpix for pic Station is ",MSEpix)
print("MSECorpts for pic Station is ",MSECorpts)
print("T Matrix for pic Station is \n",np.array(T))

(12, 6)
MSEpix for pic Station is  0.05727981
MSECorpts for pic Station is  5.185799912239278
T Matrix for pic Station is 
 [[  0.98723762  -0.37455685  70.94484564]
 [  0.37046499   0.89740519 -71.68947094]]


In [25]:
#plt.imsave('results/Station1_transformed.jpg',T_image,cmap='gray')